make exiting witch ctrl+c working

diff --git a/linux/compilecpp b/linux/compilecpp
--- a/linux/compilecpp
+++ b/linux/compilecpp
@@ -14,6 +14,14 @@ else
 	out_folder=./bin/"$1"
 fi
 
+# make cleanup function which prevent progress bar from not killing
+function cleanup() {
+  printf "\033[2K\r"
+  kill $pid
+  exit
+}
+
+trap cleanup INT
 
 # Start the progress bar in a subshell
 (
@@ -39,9 +47,9 @@ fi
     sleep 0.2
 
     # Update the position and direction
-    if [ $position -eq $(($length - 2)) ]; then
+    if [ $position -eq $(($length)) ]; then
       direction=-1
-    elif [ $position -eq 2 ]; then
+    elif [ $position -eq 0 ]; then
       direction=1
     fi
     position=$(($position + $direction))
@@ -57,7 +65,7 @@ g++ "$1".cpp -Wall -Wextra -Werror -pedantic -std=c++20 -o "$out_folder" 2> /tmp
 # Check the exit status of the main program
 status=$?
 
-# Kill the subshell if the main program finishes successfully
+# Kill the subshell if the main program finishes
 if [[ $status -eq 0 || $status -eq 1 ]]; then
   printf "\033[2K\r"
   kill $pid
